app/urls.py
from django.urls import path 
from . import views 
 
app_name = 'app' 
urlpatterns = [
    #URL PRINCIPALES
    path('', views.Index, name='index'), 
    #Inicio de sesión
    path('login/',views.Form_login, name = 'form_login'),
    path('inicio_sesion/',views.Inicio_sesion, name = 'inicio_sesion'),
    #Cerrar sesión
    path('logout/', views.Cerrar_sesion, name='cerrar_sesion'),
    #Perfiles
    path('vista_profesor/', views.Vista_profesor, name='vista_profesor'),
    path('vista_estudiante/', views.Vista_estudiante, name = 'vista_estudiante'),
    path('Vista_administrador/', views.Vista_administrador, name='Vista_administrador'),

    #URL JUAN PABLO
    path('Ver_lista_grupos/', views.Ver_lista_grupos, name = 'Ver_lista_grupos'),
    path('Ver_grupo_profesor/<str:codigo>/', views.Ver_grupo_profesor, name = 'Ver_grupo_profesor'),

    path('Crear_actividad_form/<str:codigo>/', views.Crear_actividad_form, name='Crear_actividad_form'),
    path('Crear_actividad_profesor/<str:codigo>/', views.Crear_actividad_profesor, name = 'Crear_actividad_profesor'),

    path('Ver_Estudiante_profesor/<int:id>/', views.Ver_Estudiante_profesor, name = 'Ver_Estudiante_profesor'),
    path('Ver_Actividad_Profesor/<int:id>/', views.Ver_Actividad_Profesor, name = 'Ver_Actividad_Profesor'),

    path('Editar_actividad/<str:actividad>/', views.Editar_actividad_form, name='Editar_actividad_form'),
    path('Editar_actividad_profesor/<str:actividad>/', views.Editar_actividad_profesor, name = 'Editar_actividad_profesor'),

    path('Calificar_actividad_form/<int:id>/', views.Calificar_actividad_form, name='Calificar_actividad_form'),
    path('Calificar_Actividad_Profesor/<int:id>/', views.Calificar_Actividad_Profesor, name = 'Calificar_Actividad_Profesor'),



#URL FELIPE
    # ESTUDIANTE
    path('Ver_Lista_de_Grupos_Estudiante/', views.Ver_Lista_de_Grupos_Estudiante, name = 'Ver_Lista_de_Grupos_Estudiante'),
    path('Ver_grupo_Estudiante/<int:id_estudiantegrupo>/',views.Ver_Grupo_Estudiante, name = 'Ver_Grupo_Estudiante'),

    #VISTA ESTUDIANTE (ADMINISTRADOR)
    path('Lista_estudiante_Admin/', views.Lista_estudiante_Admin, name='Lista_estudiante_Admin'), 
    path('Crear_estudiante_admin_form/', views.form_crear_estudiante, name='form_crear_estudiante'),
    path('Crear_estudiante_admin/', views.Crear_estudiante_admin, name='Crear_estudiante_admin'),
    path('form_editar_Estudiante/<str:nombre>/', views.form_editar_Estudiante, name='form_editar_Estudiante'),
    path('Editar_Estudiante/<int:id>/', views.Editar_Estudiante, name='Editar_Estudiante'),
    
#URL MÓNICA

    #URL VISTA PROFESOR
    path('Ver_lista_Grupos_Admin/', views.Ver_lista_Grupos_Admin, name='Ver_lista_Grupos_Admin'),

    path('eliminargrupo/<int:id>/', views.eliminargrupo, name='eliminargrupo'),
    path('eliminar_grupo_post/<int:id>/', views.eliminar_grupo_post, name='eliminar_grupo_post'),

    path('verlistadeprofes/', views.verlistadeprofes, name='verlistadeprofes'),
    
    #URL LISTA DE GRUPOS
    path('Vergrupoadmini/<str:codigo>/', views.Vergrupoadmini, name='Vergrupoadmini'),
    path('eliminarestudiante/<int:id>/', views.eliminarestudiante, name='eliminarestudiante'),
    path('eliminar_estudiante_post/<int:id>/', views.eliminar_estudiante_post, name='eliminar_estudiante_post'),

    path('form_agregar_grupo/', views.form_agregar_grupo, name='form_agregar_grupo'),
    path('agregar_grupo/', views.agregar_grupo, name='agregar_grupo'),

    path('Editargrupo/<str:codigo>/', views.form_Editargrupoadmi, name='form_Editargrupoadmi'),
    path('Editargrupoadmi/<str:codigo>/', views.Editargrupoadmi, name='Editargrupoadmi'),

    path('Agregarestudiantenuevo/<str:codigo>/', views.form_AgregarEstudiante, name='form_AgregarEstudiante'),
    path('AgregarEstudiante/<int:id>/', views.AgregarEstudiante, name='AgregarEstudiante'),

    #URL VER LISTA DE PROFESORES
    path('verlistadeprofes/', views.verlistadeprofes, name='verlistadeprofes'),
    path('Verprofesoradmi/<int:id>/', views.Verprofesoradmi, name='Verprofesoradmi'),

    path('formCrearprofesor/', views.form_crearprofesor, name='form_crearprofesor'),
    path('Crearprofesor/', views.Crearprofesor, name='Crearprofesor'),
    
]

projectcloud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/templates/app/10_verlistadeprofes.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <title>LISTA DE PROFESORES</title>
  </head>
  <head>
    <link rel="stylesheet" href="{% static 'app/css/estilo_10.css' %}" />

    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Changa:wght@200;400&family=Oi&family=Roboto:wght@100&display=swap"
      rel="stylesheet"
    />
    <!--Fuentes de ADMINISTRADOR cabecera de pag  -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2? family = Rokkitt & display = swap"
      rel="hoja de estilo "
    />
    <!-- Iconos -->
    <link
      rel="stylesheet"
      href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
      integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
      crossorigin="anonymous"
    />
    <!-- Fuente changa -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Changa:wght@200;300&family=Rokkitt&display=swap"
      rel="stylesheet"
    />
  </head>

  <body>

        <div class="contenedor">
        <div class="encabezado">
            <div class="titulos">
            <h1>Ver Lista de Profesores (Administrador)</h1>
            </div>

            <div class="logo">
            <img src="{% static 'app/img/Logo.png' %}" />
            </div>
        </div>

        <div class="tabla">
            <table>
                <tr>
                    <th>Apellidos</th>
                    <th>Nombres</th>
                    <th>Email</th>
                    <th></th>
                </tr>
                {% for lista in profesores %}
                <tr>
                    <td>{{ lista.user.last_name }}</td>
                    <td>{{ lista.user.first_name }}</td>
                    <td>{{ lista.user.email }}</td>
                    <td>
                        <a href="{% url 'app:Verprofesoradmi' lista.id %}" ><i class="fas fa-eye"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="pie">
            <a href="{% url 'app:Vista_administrador' %}">
            <button class="btnVolver">Volver</button>
            </a>
            <div class="agregar_profesor">
            <a href="{% url 'app:form_crearprofesor' %}"><i class="fas fa-plus">Crear Profesor</i></a>
            </div>      
        </div>
    </div>
  </body>
</html>

app/templates/app/11_Verprofesoradmi.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <title>VER PROFESOR</title>
  </head>
  <head>
    <link rel="stylesheet" href="{% static 'app/css/estilos_11.css' %}" />

    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Changa:wght@200;400&family=Oi&family=Roboto:wght@100&display=swap"
      rel="stylesheet"
    />
    <!--Fuentes de ADMINISTRADOR cabecera de pag  -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2? family = Rokkitt & display = swap"
      rel="hoja de estilo "
    />
    <!-- Iconos -->
    <link
      rel="stylesheet"
      href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
      integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
      crossorigin="anonymous"
    />
    <!-- Fuente changa -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Changa:wght@200;300&family=Rokkitt&display=swap"
      rel="stylesheet"
    />
  </head>

  <body>
        <div class="contenedor">
            <div class="encabezado">
                <div class="titulos">
                    <h1>Ver Profesor (Administrador)</h1>
                </div>

                <div class="logo">
                <img src="{% static 'app/img/Logo.png' %}" />
                </div>
            </div>

            <div class="ID">
              <h1>Profesor: {{profesor.user.last_name}} {{profesor.user.first_name}}</h1> </h1>
              <h2>Email: {{profesor.user.email}}</h2>
            </div>

            <div class="tabla">
              <table>
                  <tr>
                    <th>Semestre</th>
                    <th>Código</th>
                    <th>Asignatura</th>
                    <th>Cantidad de Estudiantes</th>
                  </tr>
                  {%for listamaterias in grupo.all %}
                  <tr>
                    <td>{{listamaterias.semestre}}</td>
                    <td>{{listamaterias.codigo}}</td>
                    <td>{{listamaterias.asignatura}}</td>
                    <td>{{listamaterias.estudiantesgrupo.all|length}}</td>
                  </tr>
                  {% endfor %}
              </table>
            </div>

            <div class="footer">
              <a href="{% url 'app:verlistadeprofes' %}">
                <button class="btnVolver">Volver</button>
              </a>   
            </div>
        </div>
    </body>
</html>

app/templates/app/17.1 Ver Actividad Profesor.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
  <title>VER ACTIVIDAD</title>
</head>

<head>
  <link rel="stylesheet" href="{% static 'app/css/estilo_17.1.css' %}" />

  <link rel="preconnect" href="https://fonts.gstatic.com" />
  <link
    href="https://fonts.googleapis.com/css2?family=Changa:wght@200;400&family=Oi&family=Roboto:wght@100&display=swap"
    rel="stylesheet" />
  <!--Fuentes de ADMINISTRADOR cabecera de pag  -->
  <link rel="preconnect" href="https://fonts.gstatic.com" />
  <link href="https://fonts.googleapis.com/css2? family = Rokkitt & display = swap" rel="hoja de estilo " />
  <!-- Iconos -->
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
  <!-- Fuente changa -->
  <link rel="preconnect" href="https://fonts.gstatic.com" />
  <link href="https://fonts.googleapis.com/css2?family=Changa:wght@200;300&family=Rokkitt&display=swap"
    rel="stylesheet" />
</head>

<body>
  <div class="contenedor">
    <div class="encabezado">
      <div class="titulos">
        <h1>Ver Actividad (Profesor)</h1>
      </div>

      <div class="logo">
        <img src="{% static 'app/img/Logo.png' %}" />
      </div>
    </div>

    <div class="tabla">
      <table>
        <tr>
          <th colspan="3">VER ACTIVIDAD</th>
        </tr>
        <tr>
          <th colspan="3">GRUPO {{ grupo }}</th>
        </tr>
        <tr>
          <td> <b>Codigo</b> </td>
          <td> <b>Asignatura</b> </td>
          <td> <b>Semestre</b> </td>
        </tr>

        <tr>
          <td>{{actividad.grupo.codigo}}</td>
          <td>{{actividad.grupo.asignatura}}</td>
          <td>{{actividad.grupo.semestre}}</td>
        </tr>


      </table>
      <br>
      <table>
        <tr>
          <th colspan="4">LISTA DE ESTUDIANTES</th>
        </tr>
        <tr>
          <td> <b>Apellidos</b> </td>
          <td> <b>Nombres</b> </td>
          <td> <b>Nota</b> </td>
          <td></td>
        </tr>
        {% for estudiantes in actividad.notasactividad.all %}
        <tr>
          <td>{{estudiantes.estudiante_grupo.estudiante.user.last_name}}</td>
          <td>{{estudiantes.estudiante_grupo.estudiante.user.first_name}}</td>
          <td>{{estudiantes.valor}}</td>
          <td><a href="{% url 'app:Calificar_actividad_form' estudiantes.id %}"><i class="fas fa-check"></i></a></td>
        </tr>
        {% endfor %}

      </table>
    </div>

    <div class="btnVolver">
      <a href="{% url 'app:Ver_grupo_profesor' actividad.grupo.codigo %}"> <button>Volver</button> </a>
    </div>

    </div>

  </div>
</body>

</html>

app/templates/app/19.1 Lista de Grupos Profesor.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
  <title>LISTA DE GRUPOS</title>
</head>

<head>
  <link rel="stylesheet" href="{% static 'app/css/estilo_19.1.css' %}" />

  <link rel="preconnect" href="https://fonts.gstatic.com" />
  <link
    href="https://fonts.googleapis.com/css2?family=Changa:wght@200;400&family=Oi&family=Roboto:wght@100&display=swap"
    rel="stylesheet" />
  <!--Fuentes de ADMINISTRADOR cabecera de pag  -->
  <link rel="preconnect" href="https://fonts.gstatic.com" />
  <link href="https://fonts.googleapis.com/css2? family = Rokkitt & display = swap" rel="hoja de estilo " />
  <!-- Iconos -->
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
  <!-- Fuente changa -->
  <link rel="preconnect" href="https://fonts.gstatic.com" />
  <link href="https://fonts.googleapis.com/css2?family=Changa:wght@200;300&family=Rokkitt&display=swap"
    rel="stylesheet" />
</head>

<body>
  <div class="contenedor">
    <div class="encabezado">
      <div class="titulos">
        <h1>Ver Lista de Grupos (Profesor)</h1>
      </div>

      <div class="logo">
        <img src="{% static 'app/img/Logo.png' %}" />
      </div>
    </div>

    <div class="tabla">
      <table>

        <tr>
          <th>Semestre</th>
          <th>Código del grupo</th>
          <th colspan="2">Asignatura</th>
        </tr>
        {%for listamaterias in materias %}
        <tr>
          <td>{{listamaterias.semestre}}</td>
          <td>{{listamaterias.codigo}}</td>
          <td>{{listamaterias.asignatura}}</td>
          <td>
            <a href="{% url 'app:Ver_grupo_profesor' listamaterias.codigo %}"><i class="fas fa-eye"></i></a>
          </td>
        </tr>
        {% endfor %}
        
      </table>
    </div>
    <div class="pie">
       <a href="{% url 'app:vista_profesor' %}">
        <button class="btnVolver">Volver</button>
      </a>

    </div>
  </div>
</body>

</html>

app/templates/app/61eliminarestudiante.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <title>VER GRUPO</title>
  </head>
  <head>
    <link rel="stylesheet" href="{% static 'app/css/estilo_61.css' %}" />

    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Changa:wght@200;400&family=Oi&family=Roboto:wght@100&display=swap"
      rel="stylesheet"
    />
    <!--Fuentes de ADMINISTRADOR cabecera de pag  -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2? family = Rokkitt & display = swap"
      rel="hoja de estilo "
    />
    <!-- Iconos -->
    <link
      rel="stylesheet"
      href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
      integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
      crossorigin="anonymous"
    />
    <!-- Fuente changa -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Changa:wght@200;300&family=Rokkitt&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <div class="contenedor">
      <div class="encabezado">
        <div class="titulos">
            <h1>Eliminar Estudiante (ADMINISTRADOR)</h1>
        </div>
        <div class="logo">
          <img class="logo" src="{% static 'app/img/Logo.png' %}">
        </div>
      </div>

      <div class='campos'>

        <h3>Está seguro de que desea eliminar el estudiante "{{estudiante.estudiante.user.last_name}} {{estudiante.estudiante.user.first_name}}"?</h3>
        <div class="acciones">

          <a href="{% url 'app:eliminar_estudiante_post' estudiante.id %}">
            <button>SI</button>
          </a>
          
          <a href="{% url 'app:Ver_lista_Grupos_Admin' %}">
            <button>NO</button>
          </a>

          <br>
          {% if error %}
          <span class="error">{{error}}</span>
          {% endif %}  
        </div>
      </div>
    </div>
  </body>
</html>

app/templates/app/6Vergrupoadmini.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <title>VER GRUPO</title>
  </head>
  <head>
    <link rel="stylesheet" href="{% static 'app/css/estilo_6.css' %}" />

    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Changa:wght@200;400&family=Oi&family=Roboto:wght@100&display=swap"
      rel="stylesheet"
    />
    <!--Fuentes de ADMINISTRADOR cabecera de pag  -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2? family = Rokkitt & display = swap"
      rel="hoja de estilo "
    />
    <!-- Iconos -->
    <link
      rel="stylesheet"
      href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
      integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
      crossorigin="anonymous"
    />
    <!-- Fuente changa -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Changa:wght@200;300&family=Rokkitt&display=swap"
      rel="stylesheet"
    />
  </head>

  <body>
        <div class="contenedor">
            <div class="encabezado">
                <div class="titulos">
                    <h1>Ver Grupo (Administrador)</h1>
                </div>

                <div class="logo">
                  <img src="{% static 'app/img/Logo.png' %}" >
                </div>
            </div>

            <div class="info">
              <h3>Código del Grupo: {{ group.codigo }} </h3>
              <h3>Asignatura: {{ group.asignatura }}</h3>  </h3>
              <h3>Profesor: {{ group.profesor.user.first_name }} {{ group.profesor.user.last_name }} </h3>
            </div>

            <div class="tabla">
              <table>
                  <tr>
                    <th>Apellidos</th>
                    <th>Nombres</th>
                    <th>Correo Electrónico</th>
                    <th></th>
                  </tr>
                  {% for estudiante in estudiantes %}
                  <tr>
                    <td>{{estudiante.estudiante.user.last_name}}</td>
                    <td>{{estudiante.estudiante.user.first_name}}</td>
                    <td>{{estudiante.estudiante.user.email}}</td>
                    <td>
                      <a href="{% url 'app:eliminarestudiante' estudiante.id %}"><i class="fas fa-trash"></i></a>
                    </td>
                  </tr>
                  {% endfor %}
                  
              </table>
            </div>

            <div class="footer">
              <a href="{% url 'app:Ver_lista_Grupos_Admin' %}">
                <button class="btnVolver">Volver</button>
              </a>
              <div class="Agregar_estudiante">
                <a href="{% url 'app:form_AgregarEstudiante' group.codigo %}"><i class="fas fa-plus">Agregar estudiante</i></a>
                
              </div>      
            </div>
        </div>
    </body>
</html>

app/templates/app/Vista_administrador.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <title>PERFIL ADMINISTRADOR</title>
</head>
<head>
    <link rel="stylesheet" href="{% static 'app/css/estilos_admi.css' %}">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Changa:wght@200;400&family=Oi&family=Roboto:wght@100&display=swap" rel="stylesheet">
    <!--Fuentes de ADMINISTRADOR cabecera de pag  -->
    <link rel = "preconnect" href = "https://fonts.gstatic.com">
    <link href = "https://fonts.googleapis.com/css2? family = Rokkitt & display = swap" rel = "hoja de estilo ">
    <!-- Iconos -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <!-- Fuente changa -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Changa:wght@200;300&family=Rokkitt&display=swap" rel="stylesheet">
</head>

<body>
    <div class="contenedor">


        <div class="encabezado">

            <div class="titulo">
                <h1>ADMINISTRADOR</h1>
            </div>

            <div class="logo">
                <img class="logo" src="{% static 'app/img/Logo.png' %}">
            </div>
        </div>

        <div class="perfil">
            <div class="foto">
                <i class="fas fa-user-circle"></i>
            </div>
            
            <div class="opciones">
                <h2>{{ adminin.first_name }} {{ adminin.last_name }}</h2>
                <h2>
                    <a href="{% url 'app:cerrar_sesion' %}">Cerrar sesión</a>
                </h2>
                
            </div>
        </div>

        <div class="menu">
            <a href="{% url 'app:Ver_lista_Grupos_Admin' %}">Ver lista de grupos</a> 
            <a href="{% url 'app:verlistadeprofes' %}">Ver lista de profesores</a> 
            <a href="{% url 'app:Lista_estudiante_Admin' %}">Ver lista de estudiantes</a> 
        </div>
    </div>
</body>
</html>

app/templates/app/Vista_profesor.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <title>PERFIL PROFESOR</title>
</head>
<head>
    <link rel="stylesheet" href="{% static 'app/css/estilos_admi.css' %}">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Changa:wght@200;400&family=Oi&family=Roboto:wght@100&display=swap" rel="stylesheet">
    <!--Fuentes de ADMINISTRADOR cabecera de pag  -->
    <link rel = "preconnect" href = "https://fonts.gstatic.com">
    <link href = "https://fonts.googleapis.com/css2? family = Rokkitt & display = swap" rel = "hoja de estilo ">
    <!-- Iconos -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <!-- Fuente changa -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Changa:wght@200;300&family=Rokkitt&display=swap" rel="stylesheet">
</head>

<body>
    <div class="contenedor">

        <div class="encabezado">

            <div class="titulo">
                <h1>PROFESOR</h1>
            </div>

            <div class="logo">
                <img class="logo" src="{% static 'app/img/Logo.png' %}">
            </div>
        </div>

        <div class="perfil">
            <div class="foto">
                <i class="fas fa-user-circle"></i>
            </div>
            
            <div class="opciones">
                <h2>{{ profesor.first_name }} {{ profesor.last_name }}</h2>
                <br>
                
                <a href="{% url 'app:cerrar_sesion' %}" ><h2>Cerrar sesión</h2></a> 
            </div>
        </div>

        <div class="menu">
            <a href="{% url 'app:Ver_lista_grupos' %}" >Ver lista de grupos</a> 
        </div>

    </div>
</body>
</html>

app/templates/app/perfil_estudiante.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>PERFIL ESTUDIANTE</title>
</head>
<head>
    <link rel="stylesheet" href="{% static 'app/css/perfil_estudiante.css' %}">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Changa:wght@200;400&family=Oi&family=Roboto:wght@100&display=swap" rel="stylesheet">
    <!--Fuentes de ADMINISTRADOR cabecera de pag  -->
    <link rel = "preconnect" href = "https://fonts.gstatic.com">
    <link href = "https://fonts.googleapis.com/css2? family = Rokkitt & display = swap" rel = "hoja de estilo ">
    <!-- Iconos -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <!-- Fuente changa -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Changa:wght@200;300&family=Rokkitt&display=swap" rel="stylesheet">
</head>

<body>
    <div class="contenedor">

        <div class="encabezado">

            <div class="titulo">
                <h1>ESTUDIANTE</h1>
            </div>

            <div class="logo">
                <img class="logo" src="{% static 'app/img/Logo.png' %}">
            </div>
        </div>

        <div class="perfil">
            <div class="foto">
                <i class="fas fa-user-circle"></i>
            </div>
            
            <div class="opciones">
                <h2>
                    {{ estudiante.first_name }} {{ estudiante.last_name }} 
                </h2>
                <br>
                <h2>
                    <a href="{% url 'app:cerrar_sesion' %}">Cerrar sesión</a>
                </h2>
            </div>
        </div>

        <div class="menu">
            <a href="{% url 'app:Ver_Lista_de_Grupos_Estudiante' %}" target=" blank">Ver lista de grupos</a>
        </div>

    </div>
</body>
</html>